# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cholitouser',
            name='profile_picture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='users/profile_pictures'),
            preserve_default=False,
        ),
    ]
