# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kindOfAbuse', models.CharField(max_length=100)),
                ('kindOfAnimal', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=1)),
                ('colour', models.CharField(max_length=20)),
                ('hurt', models.BooleanField()),
                ('comments', models.TextField()),
                ('denuncedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='denuncia',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='denuncias.Place'),
        ),
    ]
