# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-22 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('in_adoption_from', models.DateTimeField()),
                ('description', models.TextField(max_length=140)),
                ('adopted', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
